console.log("hello world!")
let pesoPeca = 150
if(pesoPeca > 100) {
    console.log ("peso válido") }
else{console.log
    ("peso insuficiente!")}
let numeropeca = 10
if(numeropeca >= 10) {
    console.log ("Quantidade válida!")}
else{
    console.log ("Quantidade inválida!")}

    let nomepecas = "carburador"
    console.log ("o comprimento do nome da peça é:", nomepecas.length)
if(numeropeca.length > 3) {
        console.log ("nome inválido")
    }
else{
    console.log('peça cadastrada com sucesso!')}